# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXN430OveRS5wqwOP1oBbQ6vRDLz6Sa2
"""

# Import basic libraries
import numpy as np              # For numerical operations
import matplotlib.pyplot as plt # For displaying images

# Import dataset and model tools from TensorFlow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Load MNIST handwritten digit dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Check dataset shape
print("Training data shape:", x_train.shape)
print("Test data shape:", x_test.shape)

# Normalize pixel values from 0–255 to 0–1
x_train = x_train / 255.0
x_test = x_test / 255.0

# Reshape images to add channel dimension
# CNN expects: (samples, height, width, channels)
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# Create CNN model
model = Sequential()

# Convolution layer
model.add(Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))

# Pooling layer
model.add(MaxPooling2D((2,2)))

# Flatten layer
model.add(Flatten())

# Fully connected layer
model.add(Dense(128, activation='relu'))

# Output layer
model.add(Dense(10, activation='softmax'))

# Compile the model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the CNN model
model.fit(
    x_train,
    y_train,
    epochs=5,
    validation_data=(x_test, y_test)
)

# Select one test image
sample_image = x_test[0]

# Predict the digit
prediction = model.predict(sample_image.reshape(1,28,28,1))
predicted_digit = np.argmax(prediction)

print("Predicted Digit:", predicted_digit)

